import Head from 'next/head'
import Header from '../components/Header'
import About from '../components/About'
import Oferts from '../components/Oferts'
import Stones from '../components/Stones'
import Gallery from '../components/Gallery'
import Contact from '../components/Contact'


export default function Home() {
  return (
    <div>
      <Head >
        <title> &#128247; TERAZZO KAMIENIARSTWO &#128247; </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header/>
      </header>

      <main >
        <About/>
        <Oferts/>
        <Stones/>
        <Gallery/>
        <Contact/>
      </main>

      <footer>
        Stopka
      </footer>
    </div>
  )
}
